# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '99names' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 99names
	pod 'Gemini'

  target '99namesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '99namesUITests' do
    # Pods for testing
  end

end
